[keys.normal.space]
H = ":toggle-option lsp.display-inlay-hints"

[editor]
line-number = "relative"
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
